
function expInfo = v2K_info_setup(sjNum,sjCBO,sjAge,sjHand,numTrials)

%changed sjID to sjNum so it would be consistent with the rest of the
%functions. unless sjID was something different? - D

% TVALT-SS Experiment Information Setup
% function: CW_info_setup
% purpose:  Sets up the critical information for the color wheel experiment.
% usage:    CW_info_setup(expID,sessID,sjNum,sjAge,sjHand)

outFile = sprintf('sj%d_CBO%d_%d.mat',sjNum,sjCBO,numTrials);
trialSequenceFile = sprintf('sj%02d_trialSequences_%d.mat',sjNum,numTrials);
expInfo = struct(...
    'sjNum', sjNum,...
    'sjCBO',sjCBO,...
    'numTrials', numTrials,...
    'outFile', outFile,...
    'trialSequenceFile', trialSequenceFile,...  
    'sjAge', sjAge,...
    'sjHand', sjHand,...
    'date', datestr(now),...
    'searchRadius', 6.5,...%in degrees of visual angle
    'nExpDurations', 1,...
    'expDurations', 100,...%in ms
    'nSetSizes', 2,...
    'setSizes', [4 6],...%includes target, so 1= target only
    'nTrialType', 2,...
    'TrialType', [0 1],...%change or no? 0=no, 1=yes
    'retentInterval', 900,...
    'screenWidth', 36.5,...%in cm
    'screenHeight', 27,...%in cm
    'viewDistance', 70,...%in cm
    'feedBack', 0); %1=yes, 0 = no for main exp only

return;

%full design is set by the factorial combination of the following factors:
%tgts x flnks x nDistSets x nSearchLocs x nFlnkLocs x nExpDurations x
%nSetSizes

